const players = [
  {
    id: 1,
    ranking: 1,
    name: "Harry Kane",
    country: "England",
    image: "https://ui-avatars.com/api/?name=Harry+Kane&size=300",
    goals: 73,
    totalGames: 51,
    clubGames: 39,
    nationalGames: 12,
  },
  {
    id: 2,
    ranking: 2,
    name: "Kylian Mbappé",
    country: "France",
    image: "https://ui-avatars.com/api/?name=Kylian+Mbappe&size=300",
    goals: 59,
    totalGames: 52,
    clubGames: 43,
    nationalGames: 9,
  },
  {
    id: 3,
    ranking: 3,
    name: "Erling Haaland",
    country: "Norway",
    image: "https://ui-avatars.com/api/?name=Erling+Haaland&size=300",
    goals: 58,
    totalGames: 50,
    clubGames: 42,
    nationalGames: 8,
  },
  {
    id: 4,
    ranking: 4,
    name: "Lionel Messi",
    country: "Argentina",
    image: "https://ui-avatars.com/api/?name=Lionel+Messi&size=300",
    goals: 32,
    totalGames: 49,
    clubGames: 40,
    nationalGames: 9,
  },
  {
    id: 5,
    ranking: 5,
    name: "Lamine Yamal",
    country: "Spain",
    image: "https://ui-avatars.com/api/?name=Lamine+Yamal&size=300",
    goals: 39,
    totalGames: 48,
    clubGames: 40,
    nationalGames: 8,
  },
  {
    id: 6,
    ranking: 6,
    name: "Vinícius Júnior",
    country: "Brazil",
    image: "https://ui-avatars.com/api/?name=Vinicius+Junior&size=300",
    goals: 18,
    totalGames: 42,
    clubGames: 35,
    nationalGames: 7,
  },
  {
    id: 7,
    ranking: 7,
    name: "Jude Bellingham",
    country: "England",
    image: "https://ui-avatars.com/api/?name=Jude+Bellingham&size=300",
    goals: 16,
    totalGames: 44,
    clubGames: 36,
    nationalGames: 8,
  },
  {
    id: 8,
    ranking: 8,
    name: "Ousmane Dembélé",
    country: "France",
    image: "https://ui-avatars.com/api/?name=Ousmane+Dembele&size=300",
    goals: 35,
    totalGames: 45,
    clubGames: 37,
    nationalGames: 8,
  },
  {
    id: 9,
    ranking: 9,
    name: "Rodri",
    country: "Spain",
    image: "https://ui-avatars.com/api/?name=Rodri&size=300",
    goals: 6,
    totalGames: 31,
    clubGames: 24,
    nationalGames: 7,
  },
  {
    id: 10,
    ranking: 10,
    name: "Raphinha",
    country: "Brazil",
    image: "https://ui-avatars.com/api/?name=Raphinha&size=300",
    goals: 41,
    totalGames: 45,
    clubGames: 37,
    nationalGames: 8,
  },
  {
    id: 11,
    ranking: 11,
    name: "Robert Lewandowski",
    country: "Poland",
    image: "https://ui-avatars.com/api/?name=Robert+Lewandowski&size=300",
    goals: 41,
    totalGames: 48,
    clubGames: 40,
    nationalGames: 8,
  },
  {
    id: 12,
    ranking: 12,
    name: "Lautaro Martínez",
    country: "Argentina",
    image: "https://ui-avatars.com/api/?name=Lautaro+Martinez&size=300",
    goals: 40,
    totalGames: 46,
    clubGames: 39,
    nationalGames: 7,
  },
  {
    id: 13,
    ranking: 13,
    name: "Julián Álvarez",
    country: "Argentina",
    image: "https://ui-avatars.com/api/?name=Julian+Alvarez&size=300",
    goals: 34,
    totalGames: 48,
    clubGames: 40,
    nationalGames: 8,
  },
  {
    id: 14,
    ranking: 14,
    name: "Mohamed Salah",
    country: "Egypt",
    image: "https://ui-avatars.com/api/?name=Mohamed+Salah&size=300",
    goals: 30,
    totalGames: 44,
    clubGames: 38,
    nationalGames: 6,
  },
  {
    id: 15,
    ranking: 15,
    name: "Kevin De Bruyne",
    country: "Belgium",
    image: "https://ui-avatars.com/api/?name=Kevin+De+Bruyne&size=300",
    goals: 10,
    totalGames: 38,
    clubGames: 32,
    nationalGames: 6,
  },
  {
    id: 16,
    ranking: 16,
    name: "Bruno Fernandes",
    country: "Portugal",
    image: "https://ui-avatars.com/api/?name=Bruno+Fernandes&size=300",
    goals: 18,
    totalGames: 45,
    clubGames: 37,
    nationalGames: 8,
  },
  {
    id: 17,
    ranking: 17,
    name: "Khvicha Kvaratskhelia",
    country: "Georgia",
    image: "https://ui-avatars.com/api/?name=Khvicha+Kvaratskhelia&size=300",
    goals: 15,
    totalGames: 43,
    clubGames: 36,
    nationalGames: 7,
  },
  {
    id: 18,
    ranking: 18,
    name: "Phil Foden",
    country: "England",
    image: "https://ui-avatars.com/api/?name=Phil+Foden&size=300",
    goals: 17,
    totalGames: 40,
    clubGames: 34,
    nationalGames: 6,
  },
  {
    id: 19,
    ranking: 19,
    name: "Declan Rice",
    country: "England",
    image: "https://ui-avatars.com/api/?name=Declan+Rice&size=300",
    goals: 9,
    totalGames: 46,
    clubGames: 38,
    nationalGames: 8,
  },
  {
    id: 20,
    ranking: 20,
    name: "Cristiano Ronaldo",
    country: "Portugal",
    image: "https://ui-avatars.com/api/?name=Cristiano+Ronaldo&size=300",
    goals: 25,
    totalGames: 42,
    clubGames: 35,
    nationalGames: 7,
  },
];

export default players;
